name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: acrLogin
      uses: Azure/cli@v1.0.0
      with:
        # Specify the script here
        inlineScript: | 
          login_output=$(az acr login --name fancyregistry --expose-token)
          login_server=$(echo $login_output| jq '.loginServer')
          login_token=$(echo $login_output | jq '.accessToken')
          echo "::set-env name=docker_login_server::$login_server"
          echo "::set-env name=docker_login_token::$login_token"
          
          
    - name: buildingImage
      run: | 
        docker login ${{env.docker_login_server}} -u 00000000-0000-0000-0000-000000000000 -p ${{env.docker_login_token}}
        
        cd $GITHUB_WORKSPACE
        ls -al
        docker build . -t fancyregistry.azurecr.io/fancy-landing:$GITHUB_RUN_ID
        docker tag fancyregistry.azurecr.io/fancy-landing:$GITHUB_RUN_ID fancyregistry.azurecr.io/fancy-landing:latest
        docker push fancyregistry.azurecr.io/fancy-landing:$GITHUB_RUN_ID
        docker push fancyregistry.azurecr.io/fancy-landing:latest
